version: '2'
services:
  nginx:
    image: nginx:1.11.6-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/nginx/htpasswd:/etc/nginx/htpasswd
      - /srv/nginx/conf.d:/etc/nginx/conf.d
      - /srv/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/nginx/html:/usr/share/nginx/html
      - /srv/nginx/certs:/etc/nginx/certs:ro
      - /srv/nginx/log:/var/log/nginx
  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /srv/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /srv/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    depends_on:
      - docker-gen
networks:
  default:
    external:
      name: nginx-proxy
