version: '2'
services:
  web:
    image: hahoo/node-hello
    container_name: www.yourdomain.com
    restart: always
    environment:
      - VIRTUAL_HOST=www.yourdomain.com
      - LETSENCRYPT_HOST=www.yourdomain.com
      - LETSENCRYPT_EMAIL=mail@emaildomain.com
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
